@component('layouts.invoice.html.layout')
    @slot('author')
        {{ $leasePayment->property->company->name }} | {{ config('app.name') }}
    @endslot

    @slot('description')
        Receipt for property rental; Property: {{ $leasePayment->property->name }}; Lease no.: {{ $leasePayment->lease->hash_id }}; Generated by: {{ config('app.name') }}
    @endslot

    @slot('title')Receipt # {{ $leasePayment->hash_id }}@endslot

    {{-- Header --}}
    @slot('header')
        @component('layouts.invoice.html.header', ['url' => config('app.url')])
            {{ $leasePayment->property->company->name }}
        @endcomponent
    @endslot

    {{-- Body --}}
    <div>
        <p><strong>Receipt #:</strong> {{ $leasePayment->hash_id }}</p>
        <p><strong>Date:</strong> {{ $leasePayment->formattedPaidAt }}</p>
        <p><strong>Name:</strong> {{ $leasePayment->invoice->user->name }}</p>
    </div>
    <hr>

    @component('layouts.invoice.html.table')
        <table>
            <caption>
                Payment Details
            </caption>
            <tr>
                <th scope="row" class="text-left" width="50%">Property</th>
                <td class="text-right">{{ $leasePayment->property->name }}</td>
            </tr>
            <tr>
                <th scope="row" class="text-left" width="50%">Rent for</th>
                <td class="text-right">{{ $leasePayment->invoice->formattedInvoiceMonth }}</td>
            </tr>
            <tr>
                <th scope="row" class="text-left">Amount</th>
                <td class="text-right">{{ $leasePayment->formattedAmount }}</td>
            </tr>
            <tr>
                <th scope="row" class="text-left" width="50%">Processed by</th>
                <td class="text-right">{{ $leasePayment->admin->name }}</td>
            </tr>
        </table>
    @endcomponent

    {{-- Footer --}}
    @slot('footer')
        @component('layouts.invoice.html.footer')
            &copy; {{ date('Y') }} {{ $leasePayment->property->company->name }}. All rights reserved.
        @endcomponent
    @endslot
@endcomponent
