@component('layouts.invoice.html.layout')
    @slot('author')
        {{ $leasePayment->property->company->name }} | {{ config('app.name') }}
    @endslot

    @slot('description')
        Receipt for property rental; Property: {{ $leasePayment->property->name }}; Lease no.: {{ $leasePayment->lease->hash_id }}; Generated by: {{ config('app.name') }}
    @endslot

    @slot('title')Receipt # {{ $leasePayment->hash_id }}@endslot

    {{-- Header --}}
    @slot('header')
        @component('layouts.invoice.html.header', ['url' => config('app.url')])
            {{ $leasePayment->property->company->name }}
        @endcomponent
    @endslot

    {{-- Body --}}
    <div>
        <div>
            <div><strong>Receipt #:</strong></div>
            <p>{{ $leasePayment->hash_id }}</p>
        </div>
        <div>
            <div><strong>Date:</strong></div>
            <p>{{ $leasePayment->formattedPaidAt }}</p>
        </div>
        <div>
            <div><strong>Name:</strong></div>
            <p>{{ $leasePayment->invoice->user->name }}</p>
        </div>
    </div>
    <hr>

    @component('layouts.invoice.html.table')
        <table>
            <thead>
            <tr>
                <th>Description</th>
                <th>Date</th>
                <th>Amount</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    {{ $leasePayment->property->name }} - (Property rent)
                </td>
                <td>{{ $leasePayment->invoice->formattedInvoiceMonth }}</td>
                <td>{{ $leasePayment->formattedAmount }}</td>
            </tr>
            <tr>
                <td></td>
                <th scope="row">Total</th>
                <td>{{ $leasePayment->formattedAmount }}</td>
            </tr>
            </tbody>
        </table>
    @endcomponent

    <hr>

    {{-- Meta --}}
    <div>
        <div><strong>Processed by</strong></div>
        <p>{{ optional($leasePayment->admin)->name }}</p>
    </div>
@endcomponent
