@component('layouts.invoice.html.layout')
    @slot('author')
        {{ $utilityPayment->property->company->name }} | {{ config('app.name') }}
    @endslot

    @slot('description')
        Receipt for utility {{ $utilityPayment->utility->name }}; Property: {{ $utilityPayment->property->name }}; Lease no.: {{ $utilityPayment->lease->hash_id }}; Generated by: {{ config('app.name') }}
    @endslot

    @slot('title')Receipt # {{ $utilityPayment->hash_id }}@endslot

    {{-- Header --}}
    @slot('header')
        @component('layouts.invoice.html.header', ['url' => config('app.url')])
            {{ $utilityPayment->property->company->name }}
        @endcomponent
    @endslot

    {{-- Body --}}
    <div>
        <p><strong>Receipt #:</strong> {{ $utilityPayment->hash_id }}</p>
        <p><strong>Date:</strong> {{ $utilityPayment->formattedPaidAt }}</p>
        <p><strong>Name:</strong> {{ $utilityPayment->invoice->user->name }}</p>
    </div>
    <hr>

    @component('layouts.invoice.html.table')
        <table>
            <caption>
                Payment Details
            </caption>
            <tr>
                <th scope="row" class="text-left" width="50%">Property</th>
                <td class="text-right">{{ $utilityPayment->property->name }}</td>
            </tr>
            <tr>
                <th scope="row" class="text-left" width="50%">Utility</th>
                <td class="text-right">{{ $utilityPayment->utility->name }}</td>
            </tr>
            <tr>
                <th scope="row" class="text-left" width="50%">For</th>
                <td class="text-right">{{ $utilityPayment->invoice->formattedInvoiceMonth }}</td>
            </tr>
            <tr>
                <th scope="row" class="text-left">Amount</th>
                <td class="text-right">{{ $utilityPayment->formattedAmount }}</td>
            </tr>
            <tr>
                <th scope="row" class="text-left" width="50%">Processed by</th>
                <td class="text-right">{{ $utilityPayment->admin->name }}</td>
            </tr>
        </table>
    @endcomponent

    {{-- Footer --}}
    @slot('footer')
        @component('layouts.invoice.html.footer')
            &copy; {{ date('Y') }} {{ $utilityPayment->property->company->name }}. All rights reserved.
        @endcomponent
    @endslot
@endcomponent
